if (self.CavalryLogger) { CavalryLogger.start_js(["plny\/"]); }

__d("XMediaManagerControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f){a=b("jsRouteBuilder")("/creatorstudio/{?*tab_route}/",Object.freeze({override_mweb_check:!1,open_bulk_upload_panel:!1,mta_onboarding_includes_brand_collabs:!1,open_videolist_creation_dialogue:!1,open_basic_post_composer:!1,open_igtv_uploader:!1}),void 0);c=a;e.exports=c}),null);
__d("EventCometComposerCreateRendererQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"4343855869021914",metadata:{},name:"EventCometComposerCreateRendererQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("EventCometComposerCreateDialog.entrypoint",["JSResourceForInteraction","WebPixelRatio","EventCometComposerCreateRendererQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a={getPreloadProps:function(a){a=a.eventID;return{queries:{eventCometComposerCreateRendererQueryReference:{parameters:b("EventCometComposerCreateRendererQuery$Parameters"),variables:{eventID:a,privacySelectorRenderLocation:"COMET_COMPOSER",scale:b("WebPixelRatio").get()}}}}},root:b("JSResourceForInteraction")("EventCometComposerCreateDialog.react").__setRef("EventCometComposerCreateDialog.entrypoint")};e.exports=a}),null);
__d("useEventCometComposerCreationSessionID",["React","uuid"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g=b("React");function a(){var a=g.useState(b("uuid")()),c=a[0],d=a[1];a=g.useCallback(function(){d(b("uuid")())},[]);return[c,a]}}),null);
__d("useEventCometComposerDialogTrigger",["CometCardedDialog.react","EventCometComposerCreateDialog.entrypoint","EventCometComposerStrings","FeedComposerCometGlimmer.react","React","composerCometCardedDialogProps","useCometEntryPointDialog","useEventCometComposerCreationSessionID"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g=b("React");function h(a){return g.jsx(b("CometCardedDialog.react"),babelHelpers["extends"]({onClose:a.onClose,title:b("EventCometComposerStrings").createTitle},b("composerCometCardedDialogProps"),{children:g.jsx(b("FeedComposerCometGlimmer.react"),{})}))}function a(a){var c=a.beginningViewState,d=a.eventID,e=a.feedQueryVariables,f=b("useEventCometComposerCreationSessionID")();a=b("useCometEntryPointDialog")(b("EventCometComposerCreateDialog.entrypoint"),{eventID:d},"button",function(a){return g.jsx(h,{onClose:a})});var i=a[0];d=a[1];var j=a[2],k=a[3];a=a[4];var l=g.useCallback(function(){i({beginningViewState:babelHelpers["extends"]({},c,{creationSessionID:f[0]}),creationSessionIDState:f,feedQueryVariables:e})},[i,f,e,c]);return[l,d,j,k,a]}}),null);
__d("EventCometFeedVariables",["WebPixelRatio"],(function(a,b,c,d,e,f){"use strict";f.getFeedVariables=a;function a(a,c,d,e){return{displayCommentsContextEnableComment:null,displayCommentsContextIsAdPreview:null,displayCommentsContextIsAggregatedShare:null,displayCommentsContextIsStorySet:null,displayCommentsFeedbackContext:null,eventID:a,feedLocation:"EVENT",feedbackSource:34,focusCommentID:(a=e)!=null?a:d,hoistedIDs:(e=c)!=null?e:[],privacySelectorRenderLocation:"COMET_STREAM",renderLocation:"event",scale:b("WebPixelRatio").get(),useDefaultActor:!1}}}),null);
__d("EventCometRouteHooks",["CometRouteURL"],(function(a,b,c,d,e,f){"use strict";f.useIsNotifRouteURL=a;function a(){var a=b("CometRouteURL").useRouteURLParams();a=a.notif_id;return a!=null}}),null);
__d("EventCometPermalinkLayout.react",["CometErrorProjectContext","CometStickyHeaderContentArea.react","CometTransientDialogProvider.react","EventCometActionContext","EventCometActionLogger","React","useEventActionLoggerParams","useIsCreationPreview"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g=b("React"),h={mechanism:"surface",surface:"permalink"};function a(a){var c=a.content,d=a.eventID;a=a.header;var e=b("useIsCreationPreview")(),f=b("useEventActionLoggerParams")(h),i=f[0];f=f[1];g.useEffect(function(){e||b("EventCometActionLogger").log(d,{acontext:i,mechanism:h.mechanism,surface:h.surface,target:"event",target_id:d,type:"view_permalink"})},[d,e,i]);return g.jsx(b("CometErrorProjectContext").Provider,{value:"events",children:g.jsx(b("EventCometActionContext").Provider,{value:f,children:g.jsx(b("CometTransientDialogProvider.react"),{children:g.jsx(b("CometStickyHeaderContentArea.react"),{header:a,rootTestID:"EventCometPermalinkPage_root",scrollKey:d,useDeprecatedStyles:!0,children:c})})})})}}),null);
__d("CometMenuItemSelectable.react",["ix","CometMenuItemBase.react","CometMenuItemIcon.react","CometToggle.react","React","TetraIcon.react","fbicon","stylex"],(function(a,b,c,d,e,f,g){"use strict";var h=b("React");function i(a,c){return!a?null:c?h.jsx(b("TetraIcon.react"),{color:"highlight",icon:b("fbicon")._(g("498146"),20)}):h.jsx(b("TetraIcon.react"),{color:"secondary",icon:b("fbicon")._(g("477820"),20)})}function a(a,c){a.aux;var d=a.icon,e=a.iconColor,f=a.iconStyle,g=a.isSelected,j=babelHelpers.objectWithoutPropertiesLoose(a,["aux","icon","iconColor","iconStyle","isSelected"]);if(d)return h.jsx(b("CometMenuItemBase.react"),babelHelpers["extends"]({},j,{"aria-checked":g,aux:a.aux!=null?a.aux(g):i(g,!0),iconNode:h.jsx(b("CometMenuItemIcon.react"),{icon:d,iconColor:e,use:f}),ref:c}));else{d=a.aux!=null?a.aux(g):i(g,!1);return h.jsx(b("CometMenuItemBase.react"),babelHelpers["extends"]({},j,{"aria-checked":g,aux:d?h.jsx("div",{className:"irj2b8pg ew0dbk1b",children:d}):void 0,ref:c}))}}c=h.forwardRef(a);e.exports=c}),null);
__d("cometSearchTypeaheadDialogAnchorUntilHeight",[],(function(a,b,c,d,e,f){"use strict";a=540;e.exports=a}),null);
__d("cometSearchEntityScopedTypeaheadDialogFallback",["CometCardedDialogLoadingState.react","React","cometSearchTypeaheadDialogAnchorUntilHeight"],(function(a,b,c,d,e,f){"use strict";var g=b("React");a=function(a){return g.jsx(b("CometCardedDialogLoadingState.react"),{anchorUntilHeight:b("cometSearchTypeaheadDialogAnchorUntilHeight"),onClose:a})};e.exports=a}),null);
__d("useSearchCometResultsTypeaheadDialogTriggerClickHandler",["React","cometSearchEntityScopedTypeaheadDialogFallback","useCometEntryPointDialog"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g=b("React");function a(a,c,d){var e={entityID:c};a=b("useCometEntryPointDialog")(a,e,"button",b("cometSearchEntityScopedTypeaheadDialogFallback"));var f=a[0];e=a[1];var h=a[2],i=a[3];a=a[4];var j=g.useCallback(function(){f({entityID:c},function(){},"comet.search_scoped."+d)},[c,f,d]);return[j,e,h,i,a]}}),null);
__d("ProfilePlusAdminActivitiesFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1794610");c=b("FalcoLoggerInternal").create("profile_plus_admin_activities",a);e.exports=c}),null);