if (self.CavalryLogger) { CavalryLogger.start_js(["B3EDa"]); }

__d("CometPageVerificationBadge_page.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"CometPageVerificationBadge_page",selections:[{alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"is_verified",storageKey:null}],type:"Page",abstractKey:null};e.exports=a}),null);
__d("PagesCometHeaderActionsMenuWrapperQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3701141543242937",metadata:{},name:"PagesCometHeaderActionsMenuWrapperQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometPageLikeButton_page.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"CometPageLikeButton_page",selections:[{alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"should_show_page_like_warning",storageKey:null},{args:null,kind:"FragmentSpread",name:"useCometPageLike_page"}],type:"Page",abstractKey:null};e.exports=a}),null);
__d("CometSuspiciousPageLikeWarningDialogQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3150607118376849",metadata:{},name:"CometSuspiciousPageLikeWarningDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("IXTCometSuspiciousPageLikeWarningDialogQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3622061641207550",metadata:{},name:"IXTCometSuspiciousPageLikeWarningDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometPageVerificationBadge.react",["CometProfileVerificationBadge.react","CometRelay","React","CometPageVerificationBadge_page.graphql"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g,h=b("React");function a(a){var c=a.page;a=a.size;c=b("CometRelay").useFragment(g!==void 0?g:g=b("CometPageVerificationBadge_page.graphql"),c);var d=c.id;c=c.is_verified===!0;return d==null||!c?null:h.jsx(b("CometProfileVerificationBadge.react"),{profileID:d,size:a})}}),null);
__d("PagesCometHeaderActionsMenuWrapper.entrypoint",["JSResourceForInteraction","PagesCometHeaderActionsMenuWrapperQuery$Parameters"],(function(a,b,c,d,e,f){"use strict";a={getPreloadProps:function(a){var c=a.isAdminView;a=a.pageID;return{queries:{pageHeaderActionsQueryReference:{parameters:b("PagesCometHeaderActionsMenuWrapperQuery$Parameters"),variables:{pageID:a,showAdminActions:c===!0}}}}},root:b("JSResourceForInteraction")("PagesCometHeaderActionsMenuWrapper.react").__setRef("PagesCometHeaderActionsMenuWrapper.entrypoint")};e.exports=a}),null);
__d("CometSuspiciousPageLikeWarningDialog.entrypoint",["CometSuspiciousPageLikeWarningDialogQuery$Parameters","JSResourceForInteraction"],(function(a,b,c,d,e,f){"use strict";a={getPreloadProps:function(a){return{extraProps:a,queries:{CometSuspiciousPageLikeWarningDialogQueryReference:{parameters:b("CometSuspiciousPageLikeWarningDialogQuery$Parameters"),variables:{pageID:a.pageID}}}}},root:b("JSResourceForInteraction")("CometSuspiciousPageLikeWarningDialog.react").__setRef("CometSuspiciousPageLikeWarningDialog.entrypoint")};e.exports=a}),null);
__d("IXTCometSuspiciousPageLikeWarningDialog.entrypoint",["IXTCometSuspiciousPageLikeWarningDialogQuery$Parameters","JSResourceForInteraction","WebPixelRatio"],(function(a,b,c,d,e,f){"use strict";a={getPreloadProps:function(a){return{extraProps:a,queries:{IXTCometSuspiciousPageLikeWarningDialogQueryReference:{parameters:b("IXTCometSuspiciousPageLikeWarningDialogQuery$Parameters"),variables:{pageID:a.pageID,scale:b("WebPixelRatio").get()}}}}},root:b("JSResourceForInteraction")("IXTCometSuspiciousPageLikeWarningDialog.react").__setRef("IXTCometSuspiciousPageLikeWarningDialog.entrypoint")};e.exports=a}),null);
__d("CometPageLikeButton.react",["ix","fbt","CometSuspiciousPageLikeWarningDialog.entrypoint","CometTrackingNodeProvider.react","IXTCometSuspiciousPageLikeWarningDialog.entrypoint","PagesCometLikeChainingContext.react","React","TetraButton.react","fbicon","gkx","qex","useCometEntryPointDialog","useCometPageLike","CometRelay","CometPageLikeButton_page.graphql"],(function(a,b,c,d,e,f,g,h){"use strict";e.exports=a;var i,j=b("React"),k="CometPageLikeButton/";function a(a){var c=a.labelIsHidden;c=c===void 0?!1:c;var d=a.location,e=a.logAction,f=a.onPress,l=a.padding,m=a.page$key;a=a.size;a=a===void 0?"large":a;m=b("CometRelay").useFragment(i!==void 0?i:i=b("CometPageLikeButton_page.graphql"),m);var n=b("useCometPageLike").useCometPageLike(m,d),o=n[0],p=n[1],q=n[2];n=p?"primary":"secondary";var r=k+n;r=j.useContext(b("PagesCometLikeChainingContext.react").PagesCometLikeChainingContext);var s=r.setShouldShowLikeChaining;r=b("useCometEntryPointDialog")(b("gkx")("1757248")?b("IXTCometSuspiciousPageLikeWarningDialog.entrypoint"):b("CometSuspiciousPageLikeWarningDialog.entrypoint"),{pageID:(r=m==null?void 0:m.id)!=null?r:""});var t=r[0];r=b("gkx")("1532627")&&!p&&(m==null?void 0:m.should_show_page_like_warning)===!0;if(o===!1)return null;var u=function(){q(),d==="page__header"&&p===!1&&s(!0),e!=null&&e(d,p),f!=null&&f()};m=function(){t({location:d,onConfirmLike:u})};return j.jsx(b("CometTrackingNodeProvider.react"),{trackingNode:p?43:42,children:j.jsx(b("TetraButton.react"),{icon:b("fbicon")._(g("509921"),16),label:p?h._("Liked"):h._("Like"),labelIsHidden:c,onPress:r&&((o=b("qex")._("1755408"))!=null?o:!0)?m:u,padding:l,reduceEmphasis:p,size:a,testid:void 0,type:n},"fanning")})}}),null);
__d("PagesCometMoreActionsButton.react",["ix","fbt","CometEntryPointPopoverTrigger.react","CometTrackingNodeProvider.react","PagesCometHeaderActionsMenuWrapper.entrypoint","React","TetraButton.react","fbicon","stylex"],(function(a,b,c,d,e,f,g,h){"use strict";e.exports=a;var i=b("React");function a(a){var c=a.isAdminView;a=a.pageID;return i.jsx(b("CometTrackingNodeProvider.react"),{trackingNode:55,children:i.jsx("div",{className:"h676nmdw j83agx80 bp9cbjyn",children:i.jsx(b("CometEntryPointPopoverTrigger.react"),{align:"middle",autoAlign:!0,entryPointParams:{isAdminView:c,pageID:a},otherProps:{isAdminView:c},popoverEntryPoint:b("PagesCometHeaderActionsMenuWrapper.entrypoint"),preloadTrigger:"button",children:function(a,c,d,e,f,j){return i.jsx(b("TetraButton.react"),{icon:b("fbicon")._(g("484386"),16),label:h._("More Actions"),labelIsHidden:!0,onHoverIn:e,onHoverOut:f,onPress:c,onPressIn:j,ref:a,size:"medium",testid:void 0,type:"secondary"})}})},"more")})}}),null);
__d("validatePhoneNumber",[],(function(a,b,c,d,e,f){"use strict";e.exports=a;function a(a){return/^[+]?[0-9()\s-.#]{7,25}$/.test(a)&&a.replace(/[^0-9]/g,"").length>=7}}),null);