if (self.CavalryLogger) { CavalryLogger.start_js(["wa8A6"]); }

__d("MWChatForceCollapseTabs.bs",["React","MWChatMultitabContext.bs","MWChatMultitabDispatcher.bs","useCometFeedNoRoutingNavigationEventLogger"],(function(a,b,c,d,e,f){"use strict";var g=b("React");function a(a){var c=b("useCometFeedNoRoutingNavigationEventLogger")(),d=g.useContext(b("MWChatMultitabContext.bs").context);return g.useCallback(function(a){c(Date.now(),"","messenger");if(d!==void 0)return b("MWChatMultitabDispatcher.bs").dispatch(void 0,d,{TAG:5,_0:a})},[d,c])}f.useHook=a}),null);
__d("MWChatForceCollapseTabs.re",["MWChatForceCollapseTabs.bs"],(function(a,b,c,d,e,f){a=b("MWChatForceCollapseTabs.bs").useHook;f.useHook=a}),null);
__d("MWChatUndoForceCollapseTabs.bs",["React","MWChatMultitabContext.bs","MWChatMultitabDispatcher.bs","useCometFeedNoRoutingNavigationEventLogger"],(function(a,b,c,d,e,f){"use strict";var g=b("React");function a(a){var c=b("useCometFeedNoRoutingNavigationEventLogger")(),d=g.useContext(b("MWChatMultitabContext.bs").context);return g.useCallback(function(a){c(Date.now(),"","messenger");if(d!==void 0)return b("MWChatMultitabDispatcher.bs").dispatch(void 0,d,{TAG:6,_0:a})},[d,c])}f.useHook=a}),null);
__d("MWChatUndoForceCollapseTabs.re",["MWChatUndoForceCollapseTabs.bs"],(function(a,b,c,d,e,f){a=b("MWChatUndoForceCollapseTabs.bs").useHook;f.useHook=a}),null);
__d("useToggleChatTabsOnMountUnmount",["CometRouteRenderType","MWChatForceCollapseTabs.re","MWChatUndoForceCollapseTabs.re","React","useShouldShowMessagingEntrypointOnCurrentRoute"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g=b("React");function a(){var a=b("useShouldShowMessagingEntrypointOnCurrentRoute")("CHAT"),c=b("CometRouteRenderType").useIsPushView(),d=b("MWChatForceCollapseTabs.re").useHook(),e=b("MWChatUndoForceCollapseTabs.re").useHook();g.useEffect(function(){a&&d(c);return function(){a&&e(c)}},[a,c,d,e])}}),null);
__d("CIXShowErrorContext",["React"],(function(a,b,c,d,e,f){"use strict";a=b("React");c=a.createContext(function(){});e.exports=c}),null);
__d("CIXCallbackKeys",[],(function(a,b,c,d,e,f){"use strict";a=Object.freeze({ON_CLOSE:"on_close",ON_COMPLETE:"on_complete",ON_ERROR:"on_error"});b=a;e.exports=b}),null);
__d("CIXFlowCallbacksContext",["React"],(function(a,b,c,d,e,f){"use strict";a=b("React");c=a.createContext({});e.exports=c}),null);
__d("CloseCIXContext",["React"],(function(a,b,c,d,e,f){"use strict";a=b("React");c=a.createContext(function(){});e.exports=c}),null);
__d("PreviousCIXScreenContext",["React"],(function(a,b,c,d,e,f){"use strict";a=b("React");c=a.createContext(function(){});e.exports=c}),null);
__d("CIXDialogScreen.react",["CIXCallbackKeys","CIXFlowCallbacksContext","CloseCIXContext","CometCardedDialog.react","CometTrackingNodeProvider.react","PreviousCIXScreenContext","React"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g=b("React"),h=650;function a(a){var c=a.children,d=a.footer,e=a.testid;e=a.title;var f=a.titleWithEntities;a=a.withBackButton;a=a===void 0?!1:a;var i=g.useContext(b("CloseCIXContext")),j=g.useContext(b("PreviousCIXScreenContext")),k=g.useContext(b("CIXFlowCallbacksContext")),l=k[b("CIXCallbackKeys").ON_CLOSE];k=g.useCallback(function(){i(),l&&l()},[i,l]);return g.jsx(b("CometTrackingNodeProvider.react"),{trackingNode:163,children:g.jsxs(b("CometCardedDialog.react"),{anchorUntilHeight:h,onBack:j,onClose:k,testid:void 0,title:e,titleWithEntities:f,withBackButton:a,withCloseButton:!0,children:[g.jsx("div",{children:c}),d==null?null:d]})})}}),null);
__d("SwitchCIXScreenContext",["React"],(function(a,b,c,d,e,f){"use strict";a=b("React");c=a.createContext(function(){});e.exports=c}),null);
__d("validateTrackingCode",[],(function(a,b,c,d,e,f){"use strict";e.exports=a;function a(a){return a!=null&&typeof a==="object"&&a.click_tracking_linkshim_cb!=null&&a.encrypted_click_tracking!=null&&a.encrypted_tracking!=null?a:null}}),null);
__d("validateAggregatedStoryTrackingNodeIndex",[],(function(a,b,c,d,e,f){"use strict";e.exports=a;function a(a){return a!=null&&typeof a==="number"?a:0}}),null);